# Generated by Django 5.0.6 on 2024-07-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_hub',
            new_name='date',
        ),
    ]
